import type { Metadata } from "next";
import localFont from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "#/components/Navbar";
import { Toaster } from "#/components/ui/toaster";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} dark`}>
          <Navbar />
          <main className="pt-32 sm:px-4 md:px-8 lg:px-16 h-screen text-gray-400">
            {children}
          </main>

          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
